### ISSUE TITLE
Floating Animation Doesn't Work In UITableViewController

### ISSUE THREAD

**Issue by afiq90** [gizmoboy7/VCFloatingActionButton#14]
Hey guys, please help me regarding floating animation doesn't working properly in UITableViewController. Below I attached the video and code for better understand : 

Video :
https://youtu.be/m-ivFXjXLOM 

Code : 

http://pastebin.com/0q9yyaG2

Thank you in advance.

**Comment by giridharvc7** [comment]
Hi, if you are using UITableViewController, try adding the button to the window

**Comment by afiq90** [comment]
do you mean  [self.aktivitiTableView.superview addSubview:floatingButton] ?

**Comment by giridharvc7** [comment]
Yes, that or try [self.window addSubview:floatingButton]
