### ISSUE TITLE
How can I make a new delegate for clicked in VCFloatingActionButton itself.

### ISSUE THREAD

**Issue by afiq90** [gizmoboy7/VCFloatingActionButton#15]
Hey guys, how can I add another delegate that when i click on VCFloatingActionButton it self? What I wanna do is when I click on VCFloationgActionButton I want present another view controller. thanks in advance.

**Comment by giridharvc7** [comment]
Hi afiq, 
I assume you are asking for a behaviour similar to the google inbox FAB. 

In the 
`-(void)handleTap:(id)sender`  function, 

```
if (_isMenuVisible)
    {
       // Add your delegate here
      // Hide the buttons 
    }
```

**Comment by afiq90** [comment]
how can I make those delegate. sorry I'm novice in iOS dev. thanks. :)

**Comment by giridharvc7** [comment]
Thats okay

In the VCFloatingActionButton.h file, add these lines  in the `@protocol`

```
@optional
-(void) didSelectMenuOptionAtIndex:(NSInteger)row;
-(void) didPressSelf; // Or anyother name you want
@end
```

.m file 

```
if(_isMenuVisible)
{
    [delegate didPressSelf];  //or the name you've given
}
```

**Comment by afiq90** [comment]
thank you, it's working now.

**Comment by giridharvc7** [comment]
You are welcome :+1:
