### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by Ketan-Wadyalkar** [gizmoboy7/VCFloatingActionButton#20]
I am getting these two error in my project after importing VCFloatingActionButton
1.
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_VCFloatingActionButton", referenced from:
      objc-class-ref in CreateServiceWizardViewController.o
ld: symbol(s) not found for architecture x86_64
2.
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by giridharvc7** [comment]
I think this is a problem with your import, are u sure the source is copied to your project?

**Comment by Ketan-Wadyalkar** [comment]
yes, i have added VCFloatingActionButton folder to my project

**Comment by Ketan-Wadyalkar** [comment]
I tried using this component in a new project also, but still i getting the same error. Could you please tell me how to use this component?

**Comment by giridharvc7** [comment]
Drag and drop the files into your xcode project, make sure you select "Copy source to folder"

**Comment by Ketan-Wadyalkar** [comment]
I have copied all the files and this issue is also solved.

**Comment by Ketan-Wadyalkar** [comment]
I tried implementing this component, i am getting '+' icon but on tap other icons are not appearing and i guess this is because you have used navigation controller and a View Controller in Storyboard and i am not using storyboard, so please tell me what changes i should make in the code??
