### ISSUE TITLE
navbar translucency = false making the button disappear

### ISSUE THREAD

**Issue by terrybu** [gizmoboy7/VCFloatingActionButton#3]
awesome job, using it in my app .. but just found something. will making the navigation bar's translucent property to false screw something up with the alignment?

Right now, the button shows correctly with translucent = true (by default) but not visible when it's false 

P.S. I'm not using auto layout. Just tableview that takes up view.frame and 
        let floatFrame = CGRectMake(UIScreen.mainScreen().bounds.size.width-44-22, UIScreen.mainScreen().bounds.size.height-44-22, 40, 44)

**Comment by terrybu** [comment]
Nvm .. doing         self.extendedLayoutIncludesOpaqueBars = true on the viewcontroller solved it!

**Comment by giridharvc7** [comment]
Glad you like the control :)
